# customized bookdown github action build
on:
  push:
    branches: main
  pull_request:
    branches: main

name: bookdown

jobs:
  bookdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
   
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Get dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libmagick++-dev libpoppler-cpp-dev texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra pandoc

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: install stuff
        run: install.packages(c("rmarkdown","bookdown","kableExtra","ggplot2","tufte","magick","pdftools"))
        shell: Rscript {0}

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build site
        run: bookdown::render_book("index.Rmd", quiet = TRUE)
        shell: Rscript {0}
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book


